export enum SyncStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  DEAD_LETTER = 'DEAD_LETTER',
}

export enum SyncType {
  SUBMIT_ANSWER = 'SUBMIT_ANSWER',
  SUBMIT_EXAM = 'SUBMIT_EXAM',
  UPLOAD_MEDIA = 'UPLOAD_MEDIA',
  ACTIVITY_LOG = 'ACTIVITY_LOG',
}
